# Generated by Django 6.0.5 on 2026-06-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField(verbose_name='تاریخ ارزش\u200cگذاری')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ارزش کل موجودی')),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='کل تعداد')),
                ('calculation_method', models.CharField(default='fifo', max_length=50, verbose_name='روش محاسبه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Inventory Valuation',
                'verbose_name_plural': 'Inventory Valuations',
                'ordering': ['-valuation_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('debit', 'بدهکار (ورود)'), ('credit', 'بستانکار (خروج)')], max_length=10, verbose_name='نوع تراکنش')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ارزش کل')),
                ('related_voucher', models.CharField(max_length=100, verbose_name='شماره سند مرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem', verbose_name='قلم موجودی')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
