# Generated by Django 6.0.5 on 2026-06-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد محصول')),
                ('category', models.CharField(choices=[('yogurt', 'ماست'), ('milk', 'شیر'), ('cheese', 'پنیر'), ('butter', 'کره'), ('dough', 'دوغ'), ('icecream', 'بستنی'), ('cream', 'خامه')], max_length=20, verbose_name='دسته بندی')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت پیش فرض')),
                ('shelf_life_days', models.IntegerField(verbose_name='عمر مفید (روز)')),
                ('storage_temp_min', models.IntegerField(verbose_name='حداقل دمای نگهداری')),
                ('storage_temp_max', models.IntegerField(verbose_name='حداکثر دمای نگهداری')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='شماره رسید')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('voucher_type', models.CharField(choices=[('purchase', 'خرید'), ('production', 'تولید داخلی'), ('transfer_in', 'انتقال از انبار دیگر'), ('return_from_customer', 'برگشت از مشتری'), ('inventory_addition', 'اضافات انبار')], default='purchase', max_length=25, verbose_name='نوع ورود')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='تامین کننده')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='شماره فاکتور')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('voucher_type', models.CharField(choices=[('sale', 'فروش'), ('transfer_out', 'انتقال به انبار دیگر'), ('return_to_supplier', 'برگشت به تامین کننده'), ('waste', 'ضایعات'), ('gift', 'هدیه/نمونه'), ('inventory_deficit', 'کسری انبار')], default='sale', max_length=25, verbose_name='نوع خروج')),
                ('customer', models.CharField(max_length=200, verbose_name='مشتری')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام واحد')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد واحد')),
                ('category', models.CharField(choices=[('weight', 'وزن'), ('quantity', 'تعداد'), ('volume', 'حجم')], max_length=20, verbose_name='دسته واحد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام انبار')),
                ('location', models.CharField(max_length=300, verbose_name='آدرس')),
                ('is_cold_storage', models.BooleanField(default=False, verbose_name='سردخانه؟')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='AutoDiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_percent', models.DecimalField(decimal_places=2, help_text='مثلاً 20 یعنی وقتی 20% از عمر محصول باقی مونده، این تخفیف اعمال شود', max_digits=5, verbose_name='آستانه درصد باقی مانده از عمر')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد تخفیف')),
                ('priority', models.IntegerField(default=1, verbose_name='اولویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل تخفیف')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='inventory.product')),
            ],
            options={
                'ordering': ['product', 'priority', 'threshold_percent'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True, verbose_name='شماره دسته')),
                ('production_date', models.DateField(verbose_name='تاریخ تولید')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='موجودی')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت تمام شده')),
                ('status', models.CharField(choices=[('available', 'موجود - قابل فروش'), ('quarantined', 'قرنطینه - در انتظار تایید کیفیت'), ('blocked', 'بلوکه - غیرقابل فروش')], default='available', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='محصول')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasure', verbose_name='واحد موجودی')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='انبار')),
            ],
        ),
        migrations.CreateModel(
            name='StockOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_reason', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('stock_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockout')),
            ],
        ),
        migrations.CreateModel(
            name='StockOutItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem')),
                ('stock_out_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockoutitem')),
            ],
        ),
        migrations.AddField(
            model_name='stockoutitem',
            name='stock_items',
            field=models.ManyToManyField(through='inventory.StockOutItemDetail', to='inventory.stockitem'),
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='ضریب تبدیل')),
                ('description', models.TextField(blank=True, verbose_name='توضیح تبدیل')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_conversions', to='inventory.unitofmeasure')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_conversions', to='inventory.unitofmeasure')),
            ],
        ),
        migrations.AddField(
            model_name='stockoutitem',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasure', verbose_name='واحد خروجی'),
        ),
        migrations.CreateModel(
            name='StockInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت تمام شده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockin')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasure', verbose_name='واحد ورودی')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='base_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasure', verbose_name='واحد پایه'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='انبار'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='انبار'),
        ),
    ]
