# Generated by Django 6.0.5 on 2026-06-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('cold', 'سردخانه'), ('dry', 'انبار خشک'), ('raw', 'انبار مواد اولیه'), ('packaging', 'انبار بسته\u200cبندی'), ('distribution', 'انبار توزیع')], default='dry', max_length=20, verbose_name='نوع انبار'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=300, verbose_name='آدرس'),
        ),
        migrations.CreateModel(
            name='StorageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سوله/بخش')),
                ('code', models.CharField(max_length=20, verbose_name='کد سوله')),
                ('temperature_min', models.IntegerField(blank=True, null=True, verbose_name='دمای حداقل (درجه سانتی\u200cگراد)')),
                ('temperature_max', models.IntegerField(blank=True, null=True, verbose_name='دمای حداکثر (درجه سانتی\u200cگراد)')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ظرفیت (کیلوگرم)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'ordering': ['warehouse', 'code'],
            },
        ),
        migrations.AddField(
            model_name='stockin',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagezone', verbose_name='سوله/بخش'),
        ),
        migrations.AddField(
            model_name='stockinitem',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagezone', verbose_name='سوله مقصد'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagezone', verbose_name='سوله/بخش'),
        ),
    ]
